<a href="https://colab.research.google.com/github/riccardo-ops/ML-pubblica/blob/main/Introduzione_a_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
tf.version

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>

# Tensori

Sono dei vettori o matrici generalizzati, con un preciso tipo di dati e una certa dimensione.

In [3]:
stringa = tf.Variable('Ciao Riccardo', tf.string)
intero = tf.Variable(32, tf.int16)
floating = tf.Variable(34.567, tf.float32)

Rango: numero di dimensioni di un tensore



In [4]:
a = tf.Variable([[1, 2, 3], [4, 5, 6]], tf.int16)
b = tf.Variable([[7, 8, 9], [10, 11, 12]], tf.int16)

In [10]:
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [15]:
type(b)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [9]:
print(tf.rank(a))

tf.Tensor(2, shape=(), dtype=int32)


In [30]:
tensore = np.full([3, 4, 7], 5)
tensore = tf.Variable(tensore)
tensore

<tf.Variable 'Variable:0' shape=(3, 4, 7) dtype=int64, numpy=
array([[[5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5]]])>

## Shape

In [12]:
a.shape

TensorShape([2, 3])

In [16]:
import numpy as np
c = np.random.randn(16).reshape(2, 4, 2)
c = tf.Variable(c, tf.int16)
type(c) # in questo modo converto un array creato con numpy in un tensore letto fa tensorflow in modo ottimale

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [17]:
c.shape

TensorShape([2, 4, 2])

In [18]:
print(c)

<tf.Variable 'Variable:0' shape=(2, 4, 2) dtype=float64, numpy=
array([[[-1.12024564, -0.44556912],
        [ 0.49215417,  0.93308808],
        [ 0.13622484, -1.0795828 ],
        [ 0.72577585,  2.2125145 ]],

       [[ 1.18302968,  0.79476133],
        [-2.20035274, -0.54373357],
        [-1.24303672,  0.50570714],
        [-2.16728404, -1.18121594]]])>


# Reshape

In [20]:
c = tf.reshape(c, [4, 2, 2])
c1 = tf.reshape(c, [1, 2, -1])
print(c, c1, sep = '\n\n')

tf.Tensor(
[[[-1.12024564 -0.44556912]
  [ 0.49215417  0.93308808]]

 [[ 0.13622484 -1.0795828 ]
  [ 0.72577585  2.2125145 ]]

 [[ 1.18302968  0.79476133]
  [-2.20035274 -0.54373357]]

 [[-1.24303672  0.50570714]
  [-2.16728404 -1.18121594]]], shape=(4, 2, 2), dtype=float64)

tf.Tensor(
[[[-1.12024564 -0.44556912  0.49215417  0.93308808  0.13622484
   -1.0795828   0.72577585  2.2125145 ]
  [ 1.18302968  0.79476133 -2.20035274 -0.54373357 -1.24303672
    0.50570714 -2.16728404 -1.18121594]]], shape=(1, 2, 8), dtype=float64)


In [31]:
# immagino di avere un enorme tensore con tante dimensioni
# l'unico modo per appiattirlo è moltiplicare tutte le sue dimensioni
tensore.shape

TensorShape([3, 4, 7])

In [32]:
# questo ha dimensioni 3, 4, e 7.

# lo scrivo in modo macchinoso
tensore = tf.reshape(tensore, 3*4*7)
print(tensore, end = '\n\n')

# in modo elegante
shape = len(tensore)
tens = tf.reshape(tensore, shape)
print(tens)

tf.Tensor(
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5], shape=(84,), dtype=int64)

tf.Tensor(
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5], shape=(84,), dtype=int64)


# Slicing

In [24]:
arr = np.arange(1,21).reshape(4, 5)
tensor = tf.Variable(arr, tf.int16)
print(tensor, tensor.shape, sep = '\n\n')

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])>

(4, 5)


In [26]:
print(tensor[2, :])

tf.Tensor([11 12 13 14 15], shape=(5,), dtype=int64)


In [27]:
print(tensor[1:3, 3:])

tf.Tensor(
[[ 9 10]
 [14 15]], shape=(2, 2), dtype=int64)
