<a href="https://colab.research.google.com/github/riccardo-ops/ML-pubblica/blob/main/Numpy_Crash_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *Scaricare numpy*

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

# *1 - Creare gli array*

In [ ]:
data = np.random.rand(2, 2, 3)
zeri = np.zeros((3, 3, 3))
uni = np.ones((2, 3, 4))
full = np.full((2, 2, 2), 5)
print(data, zeri, uni, full, sep = '\n\n\n')

[[[0.39859419 0.35713095 0.30616088]
  [0.30079052 0.37607006 0.24611719]]

 [[0.54002286 0.07182861 0.4739568 ]
  [0.56929249 0.87745037 0.8428023 ]]]


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]


In [ ]:
# full ti fa creare un array e il primo termine tra parentesi (2, 2, 2) mi rappresenta la shape del tensore
# il secondo termine, ovvero 5, lo riempe con questo numero

##*Come creo un array da un oggetto esistente?*

In [ ]:
lista = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(lista)
print(arr, type(arr), sep = '\n\n\n')

[[1 2 3 4]
 [5 6 7 8]]


<class 'numpy.ndarray'>


#*2 - Leggere gli array*

In [ ]:
# attributi importanti in numpy
shape = data.shape
size = data.size
types = data.dtype
print(shape, size, types, sep = '\n\n\n')

(2, 2, 3)


12


float64


##*Slicing*

In [ ]:
# come accedere ai diversi elementi di un array
# faccio rivedere come appariva il nostro array di partenza
data
# noto che ci sono 2 blocchi da 2 righe e 3 colonne

array([[[0.39859419, 0.35713095, 0.30616088],
        [0.30079052, 0.37607006, 0.24611719]],

       [[0.54002286, 0.07182861, 0.4739568 ],
        [0.56929249, 0.87745037, 0.8428023 ]]])

In [ ]:
blocco1 = data[0] # mi fa accedere al primo blocco
blocco_riga1 = data[0][0] # accedo alla prima riga del primo blocco
elemento_singolo = data[0][0][2] # accedo al terzo elemento del primo blocco e della prima riga

fetta = data[:1] # prendo tutti i blocchi fino all'ultimo selezionato escluso, ovvero prendo solo il primo
fetta_riga = data[0][0][:2] # prendo 000 e 001


print(blocco1, blocco_riga1, elemento_singolo, fetta, fetta_riga, sep = '\n\n')

[[0.39859419 0.35713095 0.30616088]
 [0.30079052 0.37607006 0.24611719]]

[0.39859419 0.35713095 0.30616088]

0.3061608756729184

[[[0.39859419 0.35713095 0.30616088]
  [0.30079052 0.37607006 0.24611719]]]

[0.39859419 0.35713095]


#*3 - Operazioni di base*

In [ ]:
# inizio creando due liste random
lista1 = np.random.rand(10)
lista2 = np.random.rand(10)

print(lista1, lista2, sep = '\n\n')

[0.13372319 0.37710326 0.02015408 0.26455461 0.35149773 0.67808226
 0.15832413 0.20237308 0.21446015 0.14943929]

[0.98102213 0.35120283 0.74419188 0.21884138 0.16067821 0.82829247
 0.96605613 0.02764515 0.33722522 0.98633014]


##*Matematica di base*

In [ ]:
somma = np.add(lista1, lista2) # somma
sottrazione = np.subtract(lista1, lista2) # sottrazione
prodotto = np.multiply(lista1, lista2) # prodotto
divisione = np.divide(lista1, lista2) # divisione
prod_punto_a_punto = np.dot(lista1, lista2) # fa il prodotto punto a punto, lo spiego nella cella dedicata



print(somma, sottrazione, prodotto, divisione, prod_punto_a_punto, sep = '\n\n\n')

[1.11474531 0.72830609 0.76434596 0.48339599 0.51217594 1.50637473
 1.12438026 0.23001823 0.55168537 1.13576943]


[-0.84729894  0.02590043 -0.7240378   0.04571323  0.19081952 -0.15021022
 -0.80773201  0.17472794 -0.12276507 -0.83689085]


[0.1311854  0.13243973 0.0149985  0.0578955  0.05647803 0.56165043
 0.15294999 0.00559463 0.07232137 0.14739648]


[0.13631006 1.07374777 0.02708183 1.20888749 2.187588   0.81865075
 0.16388709 7.32038363 0.63595524 0.15151042]


1.3329100690996065


In [ ]:
# esempio del prodotto punto a punto, spero sia abbastanza intuitivo
# in pratica viene fatta la somma dei prodotti tra ogni elemento degli array
a = np.arange(5)
b = np.arange(5, 10)
print(a, b, sep = '\n\n')

[0 1 2 3 4]

[5 6 7 8 9]


In [ ]:
prod = np.dot(a, b)
prod

80

In [ ]:
totale = 1*6 + 2*7 + 3*8 + 4*9
totale

80

##*Statistica di base*

In [ ]:
# prova a ricordarle nella sigla SAPLEMM
s = np.sqrt(36) # radice quadrata
a = np.abs(lista1) # valore assoluto
p = np.power(2, 7) # eleva la base 2 all'esponente 7
l = np.log(64)
e = np.exp([2, 3])
m1 = np.min(lista1)
m2 = np.max(lista1)


print(s, a, p, l, e, m1, m2, sep = '\n\n')

6.0

[0.13372319 0.37710326 0.02015408 0.26455461 0.35149773 0.67808226
 0.15832413 0.20237308 0.21446015 0.14943929]

128

4.1588830833596715

[ 7.3890561  20.08553692]

0.02015407884373277

0.6780822570378017


#*4 - Modificare gli array*

##*Accedere e modificare gli array*

In [ ]:
data = np.random.rand(2, 3, 4)
data

array([[[0.14624601, 0.01517962, 0.40154454, 0.97750887],
        [0.39109066, 0.83679787, 0.15509821, 0.50379522],
        [0.7497956 , 0.34703977, 0.2474782 , 0.92647252]],

       [[0.99790509, 0.43665318, 0.5134262 , 0.98088378],
        [0.17009858, 0.53353748, 0.01070232, 0.13267132],
        [0.05691559, 0.92870446, 0.79211749, 0.18236255]]])

In [ ]:
# accedo a qualsiasi elemento, fetta o blocco del mio data
# per non fare errori grossolani, lavoro su una copia del mio data di partenza
copia = np.copy(data)

In [ ]:
copia[0, 0, 1] = 1 # accedo a 001
copia

array([[[0.14624601, 1.        , 0.40154454, 0.97750887],
        [0.39109066, 0.83679787, 0.15509821, 0.50379522],
        [0.7497956 , 0.34703977, 0.2474782 , 0.92647252]],

       [[0.99790509, 0.43665318, 0.5134262 , 0.98088378],
        [0.17009858, 0.53353748, 0.01070232, 0.13267132],
        [0.05691559, 0.92870446, 0.79211749, 0.18236255]]])

In [ ]:
copia[0, 0] = 1 # prendo tutta la prima riga del primo blocco
copia

array([[[1.        , 1.        , 1.        , 1.        ],
        [0.39109066, 0.83679787, 0.15509821, 0.50379522],
        [0.7497956 , 0.34703977, 0.2474782 , 0.92647252]],

       [[0.99790509, 0.43665318, 0.5134262 , 0.98088378],
        [0.17009858, 0.53353748, 0.01070232, 0.13267132],
        [0.05691559, 0.92870446, 0.79211749, 0.18236255]]])

In [ ]:
copia[:, 1] = 11 # prendo tutti i blocchi e nella seconda riga volgio che ci sia 11
copia

array([[[ 1.        ,  1.        ,  1.        ,  1.        ],
        [11.        , 11.        , 11.        , 11.        ],
        [ 0.7497956 ,  0.34703977,  0.2474782 ,  0.92647252]],

       [[ 0.99790509,  0.43665318,  0.5134262 ,  0.98088378],
        [11.        , 11.        , 11.        , 11.        ],
        [ 0.05691559,  0.92870446,  0.79211749,  0.18236255]]])

##*Ordinare l'array*

In [ ]:
copia.sort()
copia

array([[[ 1.        ,  1.        ,  1.        ,  1.        ],
        [11.        , 11.        , 11.        , 11.        ],
        [ 0.2474782 ,  0.34703977,  0.7497956 ,  0.92647252]],

       [[ 0.43665318,  0.5134262 ,  0.98088378,  0.99790509],
        [11.        , 11.        , 11.        , 11.        ],
        [ 0.05691559,  0.18236255,  0.79211749,  0.92870446]]])

##*Modificarne la forma*

In [ ]:
data.shape

(2, 3, 4)

In [ ]:
data = data.reshape(2, 2, -1) # il -1 mi dice che in realtà lascio a numpy calcolare come mettere la dimensione mancante
data.shape # in questo caso sarà 6 perchè mantengo i due blocchi e ho 3*4 prima, dovrò avere 2*6 dopo

(2, 2, 6)

##*Aggiungere elementi al mio array*

In [ ]:
zeri = np.zeros(8)
print(zeri)
zeri = np.append(zeri, [3, 4])
print(zeri)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [ ]:
zeri = np.insert(zeri, 3, 1)
# con insert aggiungo:
# dove? in zeri
# in quale posizione? 3
# che cosa? 1
print(zeri)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 3. 4.]


#*5 - Cancellare gli array*

##*Cancellare*

In [ ]:
# immagino di voler cancellare il primo degli array
copia1 = np.copy(data)
copia1.shape
# cancello la prima riga di ogni blocco
np.delete(copia1, [0, 0])

array([0.01517962, 0.40154454, 0.97750887, 0.39109066, 0.83679787,
       0.15509821, 0.50379522, 0.7497956 , 0.34703977, 0.2474782 ,
       0.92647252, 0.99790509, 0.43665318, 0.5134262 , 0.98088378,
       0.17009858, 0.53353748, 0.01070232, 0.13267132, 0.05691559,
       0.92870446, 0.79211749, 0.18236255])

##*Salvare*

In [ ]:
np.save('array di prova', data)

In [ ]:
np.load('array di prova.npy')

array([[[0.14624601, 0.01517962, 0.40154454, 0.97750887, 0.39109066,
         0.83679787],
        [0.15509821, 0.50379522, 0.7497956 , 0.34703977, 0.2474782 ,
         0.92647252]],

       [[0.99790509, 0.43665318, 0.5134262 , 0.98088378, 0.17009858,
         0.53353748],
        [0.01070232, 0.13267132, 0.05691559, 0.92870446, 0.79211749,
         0.18236255]]])